<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="dj-book" failures="2" tests="24" name="PetTest" time="48.786" errors="0" timestamp="2024-11-08T10:30:32 IST">
  <testcase classname="api.test.DataDrivenTests" name="testPostUser" time="5.524"/>
  <testcase classname="api.test.DataDrivenTests" name="testPostUser" time="1.311"/>
  <testcase classname="api.test.DataDrivenTests" name="testPostUser" time="1.33"/>
  <testcase classname="api.test.DataDrivenTests" name="testPostUser" time="1.256"/>
  <testcase classname="api.test.DataDrivenTests" name="testPostUser" time="1.296"/>
  <testcase classname="api.test.DataDrivenTests" name="testPostUser" time="1.345"/>
  <testcase classname="api.test.DataDrivenTests" name="testPostUser" time="1.623"/>
  <testcase classname="api.test.DataDrivenTests" name="testPostUser" time="1.286"/>
  <testcase classname="api.test.DataDrivenTests" name="testPostUser" time="1.321"/>
  <testcase classname="api.test.DataDrivenTests" name="testPostUser" time="0.002">
    <failure type="java.lang.NumberFormatException" message="For input string: &amp;quot;&amp;quot;">
      <![CDATA[java.lang.NumberFormatException: For input string: ""
at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
at java.base/java.lang.Integer.parseInt(Integer.java:672)
at java.base/java.lang.Integer.parseInt(Integer.java:778)
at api.test.DataDrivenTests.testPostUser(DataDrivenTests.java:20)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testPostUser -->
  <testcase classname="api.test.DataDrivenTests" name="testDeleteUser" time="2.707"/>
  <testcase classname="api.test.DataDrivenTests" name="testDeleteUser" time="2.716"/>
  <testcase classname="api.test.DataDrivenTests" name="testDeleteUser" time="2.563"/>
  <testcase classname="api.test.DataDrivenTests" name="testDeleteUser" time="2.64"/>
  <testcase classname="api.test.DataDrivenTests" name="testDeleteUser" time="2.601"/>
  <testcase classname="api.test.DataDrivenTests" name="testDeleteUser" time="2.639"/>
  <testcase classname="api.test.DataDrivenTests" name="testDeleteUser" time="2.644"/>
  <testcase classname="api.test.DataDrivenTests" name="testDeleteUser" time="2.302"/>
  <testcase classname="api.test.DataDrivenTests" name="testDeleteUser" time="2.396"/>
  <testcase classname="api.test.DataDrivenTests" name="testDeleteUser" time="1.143">
    <failure type="java.lang.AssertionError" message="User does not exist for deletion: ">
      <![CDATA[java.lang.AssertionError: User does not exist for deletion: 
at api.test.DataDrivenTests.testDeleteUser(DataDrivenTests.java:45)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUser -->
  <testcase classname="api.test.UserTests" name="testPostUser" time="1.287"/>
  <testcase classname="api.test.UserTests" name="testGetUserByName" time="1.115"/>
  <testcase classname="api.test.UserTests" name="testUpdateUser" time="2.394"/>
  <testcase classname="api.test.UserTests" name="testDeleteUserByName" time="1.202"/>
</testsuite> <!-- PetTest -->
